apiVersion: 1
datasources:
  - access: proxy
    database: sorba_ml
    jsonData:
      httpMode: GET
    name: sorba_ml
    uid: PED5F9B837858F282
    secureJsonData:
      password: ${INFLUX_PASSWORD}
    type: influxdb
    url: http://${INFLUX_HOST}:${INFLUX_PORT}
    user: ${INFLUX_USERNAME}
  - access: proxy
    database: sorba_${ENVIRONMENT_SCOPE}
    jsonData:
      httpMode: GET
    name: hot-data
    uid: P13EEED571DAD0984
    isDefault: true
    secureJsonData:
      password: ${INFLUX_PASSWORD}
    type: influxdb
    url: http://${INFLUX_HOST}:${INFLUX_PORT}
    user: ${INFLUX_USERNAME}
  - database: ml_trainer
    jsonData:
      connMaxLifetime: 14400
      maxIdleConns: 2
      maxOpenConns: 0
    name: sorba_ml_mysql
    uid: P0FF082228D7E9F46
    secureJsonData:
      password: ${MYSQL_PASSWORD}
    type: mysql
    url: ${MYSQL_HOST}:${MYSQL_PORT}
    user: ${MYSQL_USERNAME}
deleteDatasources:
  - name: Prometheus
  - name: InfluxDB